package com.iota.iri;
import com.iota.iri.model.Hash;
import com.iota.iri.controllers.TransactionViewModel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.stream.Collectors;


public class Snapshot {
    private static final Logger log = LoggerFactory.getLogger(Snapshot.class);

    public static final Map<Hash, Long> initialState = new HashMap<>();
    public static final Snapshot latestSnapshot;
    public static final Snapshot initialSnapshot;

    static {
        initialState.put(Hash.NULL_HASH, 2659530283277761L);
        initialState.put(new Hash("VWKICVGTXD9KOHENOQLPXWW9EAMGAHEEJECQMWBCAPAXKBLWPVMYCLEXGFLNKXVTIWSOYGUARC9GLZPDW"), 1_000_000_000_000L);  // seed: BUGKFTLV9CMUCWGUQTEOBZMMQATACRBQOCFJHKFUFBFHQZFUFAXYDONXBEXXHLVKEDDJNPTUFMXDZITXE
        initialState.put(new Hash("PMRBRTNPUXZH9KPIVICKGQJXBHSPEPXOKPSOVXRWPPAYJGGAHPWQNEGDUJTOPFRPXQC9G9KQCZFRXIGEW"), 1_000_000_000_000L);  // seed: TAXXKQ9MKYLNKAFAJURCA9ZNBEVPNBNFASHKBQJTJGUBJISSSBAGQTIFHHU9TNTASXRBAQYBK9IICEXEH
        initialState.put(new Hash("PLUQFTHYODIXDXHEBPEDMA9YKSEDHXVXYIMJDKZRERKIGFXZOTGYYWYKJG9BAXEHMFFZPEWZMLETXUMMW"), 1_000_000_000_000L);  // seed: ZTDVBXUAOS9WRWXLHYYYROZWTZM9GEHO9NDQDSKNC9QLMZRLOPFWL9XHZA9LKQYDMJNXHSKSNMLIHIQKN
        initialState.put(new Hash("HOTCCQJIZZAZQBXICFMZWFTYTHFIC9WU9QHGUBGCXIMENMUXCUUXGOLMNZYEYSAVC9ULUQRHGUCXWZWEB"), 1_000_000_000_000L);  // seed: NGVWKZBVGLGYLRJMYQ9MSGR9VYQBPUVFWQQTBMOYQ9XKPZZHBM9QHSJRLJWCQCBKDUDZEWMLPNSMRUTNS
        initialState.put(new Hash("9MRLLAUFWBJAHHPIHWOPCKMXZVIVBUAZXWHFDCKUSVLJLVIKDKQBNCPTSTU9DLXUYYNOQMFXYVWMTAHZX"), 1_000_000_000_000L);  // seed: UKQT9QEDSGCHPOCTAJSGNZWPUYUIVIWLGVFGYTQ9FUILWGLRGZLNXUWHDDFGX9HVGJBICCBBBFEISO9VV
        initialState.put(new Hash("ZP9KXKKH9EBSWCAGBZYZJHDYVEVYTWWTKWXZSWWTXL9MVNCZBZTXTOGEZZ9SBTNOT9VY9EENWK9DDCETY"), 1_000_000_000_000L);  // seed: 9JOFSZVWNUUWXAMVQVWAZAGVRW9TXVTHEDTUANPSRABUCFW9JCHCGLZFXJPJVSKXMNOJDKBULCBPTGDKY
        initialState.put(new Hash("HITBPEHZCBFRVUUTMQCGG9WNMWFLBEYWLKMGYPVXCLHVIYHMWLGLPAMVVSWIMVLDPJOWUTEFXZVHRRGEB"), 1_000_000_000_000L);  // seed: BABC9ZNAOEWKVMV9YPRKMWLEOZXEXUNVHTIKQN9CVNYPSJFXPOMVZWCZ9IBCRPWJYBDWTU9LHTJWMBUXP
        initialState.put(new Hash("DCQFYXCGWI9YKOOFMSWBCPECGXKH9OCDW9BDHBZFXUA9XKLTXHAYSVQWBIC9LXYOCWLGYKKJZRJTUSXRW"), 1_000_000_000_000L);  // seed: P9QRYHXBCHKDOFECM9UVVGXMZPGOGYFCYQOZFMAQA9RDEINZVPPGZYZEGJKOFIQXA9PRGFYYDMEBHVDNY
        initialState.put(new Hash("HL9SIAJWNVBMJXCDMGDL9OVJZVM9CPOHCEODNSIW9ZMJIYSNLOWCORLDHDPJGVKFNXHOZVKBNLZKFFBCX"), 1_000_000_000_000L);  // seed: IHJRYKEABRMBVHKPOMTHWKATLUAQQCTZWRTPKFFOMWQXQTXBMZ9GCNSJNSOANESNUSWITUADLAAPKWQCS
        initialState.put(new Hash("BOXKGXBMPWUWCRZXCBSILTLLYGYVHJDBD9SDGVWWXNSFTUEUVKM9HMJM9RKPJHNMLKMHRONBQCNOPAMAC"), 1_000_000_000_000L);  // seed: S9NKYIKMYASZWZAAA9TZSVBUD9HLYJVRWAN9WMYWMKY9LLWQIPYDZUPTANAHQGQVSTKRAZKNTMNRRSXHS
        initialState.put(new Hash("YRJJCSHUQNLGPLGXUHKXATOGTIVGDBO9XESZHUNNFGAJT9ACFIXTCJFSWWMZNEWXMONZETDNMYSLDVUVA"), 1_000_000_000_000L);  // seed: WZJCGJIMAXTDUCDVXQLJBZR9EZOAAVNUSZGHBUUGANYANXWHYYQYGEQEPUJINERWCKAYHZNYORV9AWWBG
        initialState.put(new Hash("AHAG9PXMXPYJLIOHF9EEVDZLJAPRIDBOKQRYZHVJIZDMYBKIMAPKPUZAOQAZIMMAGRMGBMJQYFZZAIMCC"), 1_000_000_000_000L);  // seed: BAERZURBMPTVGNZOVQLUT9XL9IQRPZVQSZFMNSQRHUWURYYOBAQKTEBSPFQGRTQSDVXNGCSSX9LYJLUEJ
        initialState.put(new Hash("KTZYRBT9VUKHDKNBQA9TRXZUILKRLCVZBYNVYRA9JRJSDGZEU9XZCENJOWGFDGVPDLM99JQSJNENYTHRD"), 1_000_000_000_000L);  // seed: ZVLDYSEHU9ZT9HTTTNAFAIFC9QQSEBVADVKNBPJJSPXBLGZE9ALGUNVPZ9XQAWAXDTNKAHKDLMCHGQVQO
        initialState.put(new Hash("IALCAGNADTIXIEKIFEGZPBBNGQFHFSF9SH9OOMCNSXFAPFKFJTOODBQLWVKAGHHCCTW9CTEJFGPKWVBAB"), 1_000_000_000_000L);  // seed: JKJGPONLJCFXXMAQYONDZOQPSHZRXCXMQNVRXUNZRNTBEABNRWSRPYQCKSB9NIAVMRAVYQVPWLQAHZBNL
        initialState.put(new Hash("NVGRDVKLAAYK9OCVHWZIGKJOYTDQ9PZCHFQMGYXYAISBDFHYPEOCBQWILCSOXNUFIZ9OFWMSNYIGLJWUY"), 1_000_000_000_000L);  // seed: JVMEIEVZUURFBTSOQJEJAWQQUERAASPRMQUEXDLLJSTXUXCHZZPRDYTZRGQPHZCQLRBXYTASSDYAHLGIB
        initialState.put(new Hash("SRNJPHPHXFEHJFGWLSAVPVETNYZHHHPNGEGMDICIEJ9YUGAMERPW9F9ZPGMMCAVYZLUBLUOETYLXT9XRA"), 1_000_000_000_000L);  // seed: WNAPDESNFUUICCIOTANGHZBGURLDHBRJTFEK9NWNAXMQK99TNJAERZGDBB9TCXTFXDMWVAKS9ZXQETHFP
        initialState.put(new Hash("ACRYNABFQZXKKOCRVEYEDSTREOXKGLJPCHCPSUIXAUQDWIYFOAXWMBOABNIHBENMUGUTEXVXOQWJILCZW"), 1_000_000_000_000L);  // seed: DZLWNCTBU9ZZ9HXRGJLUWUWMKOPLMFEROKNUJAEPIESSMCATJLUXTDIRVNCTXQ9XHAFYOYTTZARIATUWW
        initialState.put(new Hash("BGXA9GYO9EFPPVEAZIPIBAKXTFAZUTGNLKTENYJPZVLDGUIR9BTCZNXZVMMJTYEVZGZR9RXYUXJAJBMRZ"), 1_000_000_000_000L);  // seed: 9BQJYFVHWPLQZRWXRCVKOUILUOJJ9IBSHMYRYGT9JGHKNYXUWDEONI9OIILU9MMKQSQPIUESWUPOICVSJ
        initialState.put(new Hash("LSTZNEXTEALBPUJMBEXDSCHRLASRDEYZQLZTYXUXGEBWVEWXBDXXG9A9ZABNORBS9LOAGAVXTJZVZXTFX"), 1_000_000_000_000L);  // seed: QXAQRSBETWEQUVIDDELCIAJOPNMAZXS9JARBGWRYSOZUVAQTILBPIQGSJQOUMRMEBXBGTBK9PJDRJDFJZ
        initialState.put(new Hash("FQAVRWBOTIVWHWLWUTJNNLPLZUGWUSZOFJAFIURHOIPRPEUEYMRZWIBGIEWXCG9WSCXXYKEUUEBDN9WTB"), 1_000_000_000_000L);  // seed: IXHIFMKASZINWYWMMYHQFDXGBUIXWTQJKITDXYYCGPPOQCTIGPACHVETMXLWCYRSV9TCWAWDGUAFJPLHS
        initialState.put(new Hash("NGEDPLSWDZWHYAGNWVGXMPROZBYBKBSCVIGNCPGPZSDAQQEDMPCVMUUMXOD9JACOBDLBGLMEASPAXRBYC"), 1_000_000_000_000L);  // seed: MQQEGKMLOYAH9VSITEDPHGBMVTMIMQIMGFLBVKNSMPCYCQT9HWQYWPJEPTHYSF9UA9NXYLLUGCFLETPPW
        initialState.put(new Hash("EVOEPSAFWNRZZAQBQIHEQWGHNXKJECJXIMJSHIFGSDVJNVNLIP9KQBVLGSV9QVEAGAZMLTXW9UIFNTSFD"), 1_000_000_000_000L);  // seed: OBTAJTTUSZZYYPMDIZAUQSVJESTSWKKRPJC9YOGWYGWXDDSFDCSVCPXIJIARCAFRNDEVSICOSAYRZUJEJ
        initialState.put(new Hash("OGINEREGSFRJIVZTKKT9YFYOKPVTXMAVJMVHLVL9RCGTIHBSYE9KRNYIOIHWAFSNFYGRXQDYNXQFGCDYW"), 1_000_000_000_000L);  // seed: 9ABRFWGIHSVYWBDCJAEE9YLCOTIPBQVMJTRBHJLNMNUKJ9MGJI9PLCRPSKMFWSXGRRMNSNXBGEAJLJYQC
        initialState.put(new Hash("LRWSPECNPLKQKMOPOMXEYJMRAPPNKUMEGLDUAQWHZDMBWGMHWRBZZ9SGW9GVE9ENTHQCDTRFNFPTBGXFX"), 1_000_000_000_000L);  // seed: BIYDMLTY9VJJUOQVRORQFQIWYUHWDRASHCPPFXUIFFSWZWCAOXVQJXBMXXUGZMKBUGBVSPYA9CAPZRHNC
        initialState.put(new Hash("UNK9YRKTCAIWMNNFLCTLANVBJBYQMMJWCORFAJJC9MCDIGZVRSWNG9KYOKEKZSLROJGJCAITBLHWOLNMW"), 1_000_000_000_000L);  // seed: AWGGIOXLVJN9UOJHPNVRJPD9CQRCZLSTCDPCQVNRNZYQONRZBIOTQSXLRYHBGUNRSOTMKRJ9LB9NLMESF
        initialState.put(new Hash("UYCDWHDMNNXTXWPWWWGHSH9MPGOUDGL9LBR9XCUGTTCZWMGGNENUIOPWQCG9RNEZWLTMEDWTIKEWEQIZX"), 1_000_000_000_000L);  // seed: CDSZFVWQTJVFTDOBSUJAHZQRSFCXZMKZCOVQPPKBNOV9RTLWJUMAMVLFCBYGGONF9ZGGZQHDDZUMXRPOT
        initialState.put(new Hash("RYWPNVVCIWYSFDEFVVHOAQTZHWGKVUHYGZT9FFTRDV9I9PNQET9D9VGNWBRBPVZOGDLXAHMLDZGCVTZXX"), 1_000_000_000_000L);  // seed: TPIYYHSVRVUEHOEGSKAPKZ9IQMJFQSZKWGHKNAXWOGLYDVGZBOOSXP9YWCRNBLEYSKETBNUEWSICHH9SR
        initialState.put(new Hash("NGTAUHXMUMYFDSXICQT9QEUAPLAFRMNPAVSD9JGGCFI9CPXSDOMYINOSUHOMUBYLQTCJDVHTBITOQKTDD"), 1_000_000_000_000L);  // seed: MWAFTYDZPPHCSSU9NTYOITEQ9OKE9PDBDLNJCGTKMOBYCNJKMIXZ9AECMO9ZUPUNYUUKBJRQTCBQHO9PP
        initialState.put(new Hash("BALIMJUPEIJKERONMWQSOHZ9YUFCDLEEIKJUPAV9UAAZBBHNQBVQVMEUJTJRKNPOZFHCJLXILHNIJPGG9"), 1_000_000_000_000L);  // seed: AXWSXQBKQUUDELJYXIBWIAFUQHNJKCXTRRSKGHXEYRJREKUODCNUTDRITJVT9GNHBKFGSGCVYGTC9VLUT
        initialState.put(new Hash("RGXFAFJYENYHHGORSSTNUESDBZEEXEEXDFRAKYCAXELRUSCMJNK9IVVMUFTTZROMZKUWEQFABAIPFLFCC"), 1_000_000_000_000L);  // seed: VHBDQUDM9LWETYQMLANMEQDFZTNSLTHMTKRUQIUFW9FLA9AJNPMKGSEQRUIUMZSZGKIMJGCEPYRRZHVKO
        initialState.put(new Hash("IWRAI9WXIBOXQVT9QXLBNDXJDZNIJNMPHDPDVURCORYXDHFZKQQATXSWAUZYGOMDKMZZANCIYDCXUMLLD"), 1_000_000_000_000L);  // seed: QYVKNZXZGSAXP9YEOMVEMDDZLPHZMTTXENJIQLBBRGSOWBHTSGBOCFBFYISYEVDYTWBEWPHNNDFLCGO9C
        initialState.put(new Hash("PH9ZAWXMSRHWINJGDWIDZHAXKYCPBNHJBAKLBETGYPFIFZPERBWVFOXJPVD9JPTIDH9UVZNJRFAPBFBKZ"), 1_000_000_000_000L);  // seed: KYZCHDXQPQDYBYJLKZUSOURLOMLFZEOGLTVENMQJVJZXFVT9SDWAJVFOYAISQ9DHXHPKWMVEBKLTNIOXX
        initialState.put(new Hash("PODTRKZMYLHQXVKKZVBXRCHBTHGAX9PLYCZRQTWUFVPCDIWIDXQZTOBBUNXEYDCLJEVIEEILRHQLWEMEX"), 1_000_000_000_000L);  // seed: JX9ESGEKBWHH9KXQHRBPYCCMMQ9VDOZKCDCBJUDDNMBDSVNKDEYRY9RJZJDJKMJYD9NMSJSVNATDZETGW
        initialState.put(new Hash("LATXLRZKQEAKR9MD9OIYYBHUOMILCHRIGY9TLKMBSECTB9GZAJLGIDUOODRPLMHNTDPXMDSAGLNQRWUVX"), 1_000_000_000_000L);  // seed: YLTOUUOXPGBZOVOZWMTVMULKRPBOYYCKV9TVQGXHVAZNWKHHXLXHSGB9SWL9NWWEJRBUZ9CX9QVSRVHEY
        initialState.put(new Hash("9QDDTUYKZGB9KFVV9NMJUZQFSREXHDPJULBTYPB9NQAZE9YQRNCIFCGDWQHECVLPRRVXJIDHRYKMUXPZW"), 1_000_000_000_000L);  // seed: HEQCJDFI9OUTJITQANIVAERDNXIWXSOCH9QRBTHJOUSMKVWEOWAGYERJOURSD9YSUOXHP9HDWXJUNXTAO
        initialState.put(new Hash("VVJGMCOCKGTADG9XBBXCHAGFVIOMMNXGDLJGYRMDPXTJSMBWIFFICBGCGFCTWMVZGIUFWNLHHVRVJMPBC"), 1_000_000_000_000L);  // seed: MFQSHYT9ACBVNKBEKOXQXXYORWDJMGLCBFXQBGMQOEMBLCTEUVNUQRXGRRSVANNOPALZFIANOVDZ9RGBV
        initialState.put(new Hash("Y9UTFUG9CMLYWXNKARTRKMQGC9OQ9CLYHMCVZGETIUZOEARWZPEWZ9RZAHQKKCSMPBJMXINIL9FKSUDMW"), 1_000_000_000_000L);  // seed: SZKLHCUETBQBJNPCWQFCNPNDLLJ9GURA9XCMQIGEYTLFYFOORFWRAWOUAXBCCYIVHEEGEJDU9WDTNVWY9
        initialState.put(new Hash("CJYFRIAZFRKNTAIOJ9HKCCLRCTPGZCBTAHG9GXCRUBJOURLVJLUXPIHGJPAZPGIMLLTGFZSEHOQLOOOYW"), 1_000_000_000_000L);  // seed: KZXAOQPJTKZWBEJSGQCEVW9LXIFELQGT9PPAQWJYJ9HJTNOOWYOIDCLNBJJGCJVTNMHKYXSHHYXIJBSFY
        initialState.put(new Hash("ZJMPZXSYSGYDLMSPTPLZMKBXHQLKYCICDJNTIOQGBUEQWVYOCAXSQZUVTRFJVQQIDBZUXOKWRXKOYUKFD"), 1_000_000_000_000L);  // seed: DAVLHWMIYSBBQYJTURQPOAJVWJBAXNLGILSKSQCIADKZRRRSTEKKDQPCRLNXGRDOQQSCYQSRYMSOSXPW9
        initialState.put(new Hash("IZTSTSOVG9ZRNCGVODPOUKAIFLQJZXUEFWJKRRAPGDSKISOSGIEUVAJXLFCXBRPWZGLYFNYTOJG9QRLTZ"), 1_000_000_000_000L);  // seed: HGGUPCHNFNLS9XLVAVBGZZMIGPWUBRSFQLENDMWZEVZGMLEAJUWLP9IZFOP9SKDDPUKVDXWZDWDDQFBBM
        initialState.put(new Hash("AXKTUNFWSUPUBTMJJXLBJLDTNTLIWZEUGICIJFEJTQFOLBRHK9AXK9UGZXJROZYRTCYHPWQJGDM9XJCCW"), 1_000_000_000_000L);  // seed: QWQMRZVQTYNBOZMGSZUDIFZHMVZUUMRRV9TEKMKLJOZOBXUHQGZMYVWQEKZCSCNBYRAX9ODBCFJRZQFJD
        initialState.put(new Hash("GGGBYYHHD9GEMQTVECHPUSOFJ9EJZDLMBCSRUMPKNTAKCPHHIMZBKWMFIZNNAVHFJMUGADMOEVVSHNYDC"), 1_000_000_000_000L);  // seed: XLIWVFDKRNJZAAGIFTCZTELYZMYZZPYTCCNMOXVGHEKFAWRMMJXXUDZMFBQYGTQY9YZSVRUPXMDZWGQCF
        initialState.put(new Hash("UX9LLVEFZLILNHWZ9CDWBBBZUHRLU9MZVJBWDDEMNWXGCVWAZUJ9SKNUCYUTBGILHPUGYTBNURHABZFIW"), 1_000_000_000_000L);  // seed: AAMAGTQMUMYUCSBURCMPWFLAFHDEYYKZUNEC9CKUYIMEDZL9WBGMNCOTXVRIXME9YAEENQUWQOWLLMPGF
        initialState.put(new Hash("IKSQERMUUWALOGJNUACKHARLXS99KQNN9GJMPXPDZJ99BQESBWSTQVRRGUGJTTZ9XOWYRRHPZBIPTIQVZ"), 1_000_000_000_000L);  // seed: XNKOQAZPBJD9FKECMHFAHGLLCNBXBUMVRKQWHODAV9QOCSRBNQAGBWNDQQLODCTBVOPKWCDZQUTRD9GEL
        initialState.put(new Hash("SWSVHQIRZHWTJBPEOINSB99LWUQVULTOANGYTCMFWXWIMVOMHOBVSVVH9BNNINIDSVFOE9MMXIXSHEWNX"), 1_000_000_000_000L);  // seed: RYORNDFFFUJTA9CJVRIYF9BAISJWHYXILGBPR9PKBVPFRBUFAIZBSCRJLBPKHAQZCYNGDJLEZGDZVTPRI
        initialState.put(new Hash("FAPG9ZWYYHFJSUYBJDQPCDARNTVCGXNLCHYCKHLJCPKZZKQIGYMLNJXSPM9WCDEBFKMKBFARGAUMTVRU9"), 1_000_000_000_000L);  // seed: CLFLJPX9FXCLUZDZSMCA9UXGMIBQ99CNTPOIQYWPDV9XMFJXOBWFQDJCFANVYRLAQGPUZOCGLRYOCAJZF
        initialState.put(new Hash("S9XVDJZAGYGODXXSWDTBUJIMNPMWQCOI9NIZDVSAMDHKVKBPMZFDYSOOLQCEUAFQCNFYONVBOXXFJJSVW"), 1_000_000_000_000L);  // seed: WDKE9RYLNRFJGRFLYCCC9TENKQDZRT9TOPYUBW9F9RZKIHKOZUEQWWVLVZXDN9JYYVTEXOIK9PAMSKEHL
        initialState.put(new Hash("JJVUESSSBQNVBUBREAMPXCRAMCRGKXASZIVVFZFNGWGEYQDMCLSWHYKHKMHLZJIHYRZC9RLNFSRAGSBJC"), 1_000_000_000_000L);  // seed: TIUELQZC9CSEONUBF9JEJCOXBHZM9CHCOJLJDRDXG9BHALBJTHEEYVCJAGNJFKCDG9I9QILQPRBYVOGXX
        initialState.put(new Hash("OHIEADUVGZJMAEEKRPTIHEEQTFKEEGHRSSXDJECHWUYFNPWJUSLCCFPBCBHIWDORNPLENTFMLCHBMSIIZ"), 1_000_000_000_000L);  // seed: FKOVNRZXGNDUSLNKPOVPNXFQZXTQBYGQJFZZPVLGYRNTPVETKEFACNINNBKPFVELJEXELJXETDKIMGGIG
        initialState.put(new Hash("RVSYZRHNISAUFYSVBUKRHAUEMRSPXXBFSM9CCYLEKDHRTB9YZWWEMRHQBXNFZSZKGTGNWNB9AFPXDKMYA"), 1_000_000_000_000L);  // seed: NMLLBXFTJCRPGECYWYKNDKXKKQOZSCSSBCZMSKVKIBI9MCDKGYDMHIHGMVWZRAUYYNL9UHMZKQTM9IAYR
        initialState.put(new Hash("IBKHGENR9FWCFEQGXZTLLUUDXHO9KHHUNCCASPS9STKS9GDB9PLHRCQHIWLDRQGDCSWNYMXWAXODUOFAW"), 1_000_000_000_000L);  // seed: XIVQJWNUWWSKR9OFFXDZPCXTV9LYKJAE9LPHAGQZVIUUQQF9XNRYJ9SLCIIQVXVBYQFCKCBKATRLBFRRB
        initialState.put(new Hash("CEOCUYABWCPLZGDEP9JNHNBSODFRFGRXSABRDYBNTQYNZHEWLIVXYSWFWXGYAGVREMCMTQVDZABPLYEYC"), 1_000_000_000_000L);  // seed: NI9YHKRQNLAKFEFFANUTHECHMTFAQCCGO9COUCFLDLZOY9KLVBQ9PDKSCSPCJOFEPMQRBMJIGTZZEQ9FP
        initialState.put(new Hash("OXMLWWYBDKUHIXZXQRSTGYVRBOZHLPTQDNMROMOFMMXYWCPYT9KVIIVUNCVMIPLGSADZTHEGSAFERUUE9"), 1_000_000_000_000L);  // seed: XGXAEMQUNABVLBF9FDL9SEYODQKTKVWVDGCWGCAQWMGJGSGPZVTACYJXDUPRIKEM9YCMJJIUDBDNNMRAT
        initialState.put(new Hash("LWICDZYMKNCEVVUXBVCCVPXHSNZ9VGR9X9WXKQKPUOVKPDKFVGCECMOAKOSOFBLMUZGVHKKVVJDJFLEUW"), 1_000_000_000_000L);  // seed: VW9ZPYTOVCW9UFMDOYAZDCGTKGFUS9FBVHUIEKQMMILLMDOWWNZBTYFFSLILAEKASHNHIXNLBCDBMJSYT
        initialState.put(new Hash("T9SGTPMHCCTUWQYJIMRJORFJRDHZACWXIXTVOFEEDKQENZZSELDSCOJIQAFIQDTMH9QOMJFAERAXSXEUA"), 1_000_000_000_000L);  // seed: APYENHWE9LAITYFTGJ9LOAQCLAJZ9LKGZQCDWMWMWJDXYJZUANUVIL9EHQVWGCRN9GFSCCDPHSKNVBXIQ
        initialState.put(new Hash("UGVZMHQKJMIPCZWZUWNNZH9JCNO9AVQDITKFIMQFHZEAOCLZHXJOGOQNPOMSLZVYJHHYXFJKTQLLEPBMB"), 1_000_000_000_000L);  // seed: TAWSPZXRPPOZBJT9CMYWAMFVBPGSLUPEQXSQGRVQDAANPOFQCMSAVTZWETYLTOXWWBNTQZOMMEDKZENJI
        initialState.put(new Hash("WSOUTOCHKYNIHJHZJEUOWIKHVDZ9HTNMMFUCHNOJRMOWGP9YVIGWNNOBGFCJSIXJLDUAPCBLLEQK9VHQZ"), 1_000_000_000_000L);  // seed: SBYUVRMSTFTQDXEJMWZWBSPAMUK9VQFTXKOALOPYWBPXTRLFJLKITHVHEIHJGAGBVQOHUUYCVVRWYCZDF
        initialState.put(new Hash("IKDCWOIZFGOVYDVVDNVWYZYFBGLLPXVJXNGFEPRKURFSK9QTHNGUTLCJCTTJVRNKWJB9YANQQAC9LOAKX"), 1_000_000_000_000L);  // seed: YFJRRLMNQUSBELYNEKIBHMAUAMMASHYFTGBYKKMYAVEGVRIZDLZTMZRNHRDXFGFKWDDBLPUI9IGNDKOEJ
        initialState.put(new Hash("NYHJJBGSIDFNTHHXRCSERBGNVTWJAFXPGDR9XMLNYXLUQACMABKYPPKCDUPOUC9GACTMFQJRVQWEH9RQW"), 1_000_000_000_000L);  // seed: OIMPDSEKQWSIVPTOPTTHZILPOMVFSEKNO9OISRWAXENTGKRVLBAPQFZQPHCTVPZNPHHFUOGQGXHVOKFTY
        initialState.put(new Hash("ZKDXFEAL9HHZCMBMYAOVRNOOZSPRZTECOYPZPHHALZXVLO99BIKNKHEPMTTDMNURQQSGAHNYVZUUMVHOX"), 1_000_000_000_000L);  // seed: BASFKMKKBEZYGRYZBSPHMFHWJWEDWEKJMDHBYGTNDYKIXSASDKFWH9EAGTMPJWEVNVXTI9TBVHVMBGNCD
        initialState.put(new Hash("KYAJVDSSTHXKCAKTZFILGENQNBUNNUMPZLVAL9RTVA9ORVWPCHOVGIZANFJORCSPYHYPFWYAFXKJURL9Y"), 1_000_000_000_000L);  // seed: 9ILXYLSVIFWEFPBPDDJHEYTYHBWP9AGSFNRRWC9GXYDRGAXPIIBRSEFYWRNJYWTCCPOPPZKYZCTQGSCXX
        initialState.put(new Hash("ZZIBYO9PJKXCJBKPLDLY9XALBS9CGWXHGBQCXDQOTSSCDQGGSTEWOMMOXBXOHTOKRUCGJLDCEXEVMLMOX"), 1_000_000_000_000L);  // seed: KHOGX9NUA9AQNXKPHWL9XKMIAERWBZGQ9ZWCZMXWGSLDTJSQJJBXOTOJI9TWJKMUTHYXEIRMTFMX9KSCQ
        initialState.put(new Hash("BRLDCZTVNHRRHRTJRKTSTXC9AIACRWUXMNASUCWRJFBZLNGFQMYTTGTHPQTSKTKHRBKFX9AUBEEEJCYSW"), 1_000_000_000_000L);  // seed: MCOGUHBJQN9OYJXHFIEZOQTNMQNOUHSGGUCHKICLECBJDOTOJQCJSQ9OPPSIJGJONQYDRCIJPIPVZZA9U
        initialState.put(new Hash("ZBTWCJHEJBRBZKBBGPUQDBGDVMDOANXSBBRITTJDTLYYO9IHMGYGUDOXPT9OYLWVXTAGFHRJNYBNPDCVZ"), 1_000_000_000_000L);  // seed: JWKSXEL9UZ9XVLGXDMKLBWU9BUUJJ9HVKALQS9XSWWDBFJUUJOVTFVUGYGCMPBWWZVNFKRVCFOHEKIRRO
        initialState.put(new Hash("UHKTBRSV9HMHXNJJKAHRUIUDBPDNVCQGVIHGLBFINHLDGLWU9WVYSQOZDGPZKVZDPX9UBFPNCKXDOKGWZ"), 1_000_000_000_000L);  // seed: RYGMEMWGDLLLJERNIHRAVLKQDMQ9KCJPBEPQQBQ9CHDQSCUXADZDLTASYQBPUHDPEWSTJLROFVB9ZQNVR
        initialState.put(new Hash("KZQWGMMAALPPGPKISADMKUNQXTNAPJD9SHIOKHVJZLTPCTMWMRFUHNVVKHXICXZMKJXJOAGILOZOTWWI9"), 1_000_000_000_000L);  // seed: VGMXBBSVFTRJHXOOVHZLVDRHA9HSETZQO9YQMPHDHLWIAQZWVPKBWMKKRSOXHWFLK9UQBFFMPDDQVJBGV
        initialState.put(new Hash("UYBTLWCNJECEWCMNMHPEZIWTJWRZYMVBVBAA9COK9JORWIBMEKND9JESDUPFECKSVGRYZDLTXMRMWXOFB"), 1_000_000_000_000L);  // seed: TVWFLSJJZZFRANSKOV9QHUGTQZCBQSQNDPFWIKKQTAVOAZAKQAIURSNASESVTZBGNGEOUNIDKDVTZPKWK
        initialState.put(new Hash("SDGWTOAIBFVDSPNZHUTWVAYDLQSWXMDURITTKHHEUGBMZZMAXFWPELFEKDFGJHQGDOVTSZEYNYGSGVED9"), 1_000_000_000_000L);  // seed: VBIVQPELNPNSPMWTRNOYBTOGUVLYRSXB9PKJDDWFZKJCDGLWMPZOZCCMZJ9999YMACCOYAAMKIQBCBGXO
        initialState.put(new Hash("BNGBFJPOZABHWBHZUBIVSBALIJZNPCCUBOSRLM9QSTDZIMZZSLAIIHDAJNPRYTWPRMLBXNIDZIZ9VFBID"), 1_000_000_000_000L);  // seed: SGYZFSXAY9GTSMWT9BWOXLFZUBWNYMBHFMOHROTNZYSATSREQIJXIWQFCDGXUHVZQMQVSNVXDQYLJIYOB
        initialState.put(new Hash("RPHBQOOPDLWEUXXNDKTZFNUJVGJGUNPCBSBUSGAHNEWAMJBLQQNYRBXWPRMCPEBCIUCQUPIYBRIBDSJJA"), 1_000_000_000_000L);  // seed: WCUNECUMZCPQNXNAU9KGDUBRRTJWXSNICKTWVGZGYXYICLJNGNLEVOE9PAGFK9EETUNKHUGWZGIEYLKXA
        initialState.put(new Hash("RVSOKNS9NOQZGONTCNHWUJDUQYACMTBYZADJFPNBVYNXZYRMPHGXIYJLAKIZYBHPZQATIXXNKLDJLZEKY"), 1_000_000_000_000L);  // seed: RCEVWSBSVUJPGJHWCKWLQQVLILT9ZDSHLNREFBTBAXLPNSCQUBAEBYCEPXTASRCAFR9UGDULUPXPTTXBI
        initialState.put(new Hash("ZO9ESCPFFTUBK9Q9IMOHZMQCQKPNSSE9M9TLJKYDCZAFYEAEKQMQ9KUOLFHRQXGPITMTVHJPS9JODLUAZ"), 1_000_000_000_000L);  // seed: WTYNQIVDYOMVVAYKWNFOCKGCDBSWZLMFT9TGALSJMBMCTBQFXLLSJRUXLLFQQKXYTVBN9ANPNE9MHKZTX
        initialState.put(new Hash("CLEUXWRKITNWSVDAGHNFMZUVHDPTMPPURHFYPJMLKCWVRZGKZV9ZOGDLFAJSRSDYFHPZEHLTGEPBEQXFZ"), 1_000_000_000_000L);  // seed: RPWAXKFOSHNUTJZFDDOLUTKMZPZRROSNWZKQRLXVQKNTGRAOJM9T9DCYPDSTOZOSGSIOMXAMEESX9YKVV
        initialState.put(new Hash("KGFTBXQCHAA9LXEKBULPHKVEMUUDPZUBFHGVCTOXMTGCGFVSWTHMPWTJDZSTLK9UPWGNFGFBG9UVVTZB9"), 1_000_000_000_000L);  // seed: JBJZIHUJBMKDXPXRFMPKWBQGS9LYBDEYPWVXH9WJPFKACZRGAIWNMKRZNYXDTGHTKTBUTTQTWFTSHALAR
        initialState.put(new Hash("BYHZJZIZBSBDEUNFOULCMLWVZVNF9FXWTEPQLGNDLM9QZYQTDTUESWCELAFN9ZWTMZHSWFTKKWJVQXK9X"), 1_000_000_000_000L);  // seed: UGRNSVZTAECANXIKCAXJTGBQFTTEUCTYS9UTKSBP9ESIBRJMSEDQ9FLPVJPFWGQZYFKFVXSLLBFXM9WQV
        initialState.put(new Hash("WULOTSDMRQQLXRIMXHCRRMQKBHNGBGGNSYAVM9WTMADZUAEWXJDRP9HCAWUNPSUIHFVLPVQULHKZOZXV9"), 1_000_000_000_000L);  // seed: CGAPYRJTPIVO9LEBAQFPFVBLY9PRTMSXCFKO9WPCTVXKO9CYNGWWREZZLTNUIRN9BBKAQUVTHTNKDKPSR
        initialState.put(new Hash("BAPMMKWELGWNHXFPHADGWZXHSATAOYYZVN9DQTITXOGV9BTKUBULIHZCOUAHNXCKIGSBNUVCLYLMWWBMZ"), 1_000_000_000_000L);  // seed: FEYSEMVJHEAZ9ZDKRNOSJVBOGJKKGIJJEWIK9NGNFA9LSLGKKJPZRETABYSTQT9YOBDLTKZY9YKKDLWIN
        initialState.put(new Hash("DYGVBACAELSOUQKZPERWDBEDCQIRSYZCUJR9OPPANYMCONRJQPMOLKUOOYIBJOYJTTYDGQH9Z9JWDABNW"), 1_000_000_000_000L);  // seed: HHVBI9TDIAEO9LVBXUXNLHVAOSZADSFAXSDJACGIOQMKR9MSR9XDUZIANMTSFXJ9QRBJASANSIE9WLBTB
        initialState.put(new Hash("NSJEVNWWQGTBBTRVJMWIGSRWBAGRLZZLIFKBDVKLATUDWLV9ANSBGKJIRJIBLKVOMIXGWMXAMJIZVGWT9"), 1_000_000_000_000L);  // seed: VNZQHFVJEIXDVMMNHTMOHIE9RXDIEAKSLODMFPAYEPZZMXNWCVYSXRNYZCPUUG99SDKMAAW9JUCC9LGVU
        initialState.put(new Hash("GQTNCQVFXPDNHT9WWCUMOQMSOF9NGQKBZS9OTIAPKCFKSANDBYCV9MRSADAZC9T9RQNNOUEUJMAVVBE9B"), 1_000_000_000_000L);  // seed: JVIXZZJYSFPRUVQOXOZGXKY9ECKFIJLVMZGPBDWCKZUEZWEDDHPZWOSLYSNLLTH99OYPGGSQUQVUDKXIG
        initialState.put(new Hash("HLNFGNR9JLSQWSYBNMXECDIRIRBPUOQVWRRAUINLWKEWDGEVNPTUTMN9DIVOT9V9NQCYJ9OIROVRMMCMD"), 1_000_000_000_000L);  // seed: CVHLPABHEUTHAGVONMRPJNUGLXGSXZ9QN9SJNXRFNYYNJVSCMFUJHBGWXOJ9AVIKPFZAZWKMJQEPEZNNA
        initialState.put(new Hash("ISPVRNYWLQDPTDZOZJLUONETZZYWHYYPIGBHCXXWBKTLN9SRISBTZDZHGTHINBJGQCIUDQASXML99TBMB"), 1_000_000_000_000L);  // seed: L9YWAXJFXAKXHPKYZSHPKFYTNSBLAVCANAXZFHFMOWJKXZWZOMSQCJSAD9VAEM9JCRAVCYLINABHFIKMR
        initialState.put(new Hash("FTHRGDARGSKHMRNBAPYTCEOQBUJVQTUCUI9TURZEAPNCMVCCXRJMRMZPOMYENZPFBQHTAYRCEAORESMVZ"), 1_000_000_000_000L);  // seed: FJRGUHMPGYQNINIZXYWXUCTW9LZATKDXUERHPCNEXMATFFRPAPQJHRFPBPT99SXBDBLTBZJBEASHZA9IZ
        initialState.put(new Hash("OR9DATXBHQABQLPJPUFDCL9WVKLCKRU9ZPAJLOEXSVKWOPHVUMPDPVYXPYCPUXBIKLILYDQUDTMKZXWEC"), 1_000_000_000_000L);  // seed: EIYLFDTTKODTMOULZNDCVUHWXWGY9COULJCCRKPN9C9EFL9PPKGLOSUFWRUXMZEEWYXZD9LXFEMYTIVOR
        initialState.put(new Hash("YEHOHLGPFJOHIZNIQAGH9EDMBHRMADDGMQCCMNXDBKPODQMMZYDFDEEAQNDSDRTALEQDJXMWRNOYPOGKX"), 1_000_000_000_000L);  // seed: XVORFAMYOUOXPZNITQRRQBDOQQBUFIIJCEIUXGXAJ9ZN9IODZNJNKJC9UJAKVDWFWSSNZLWR9DMNDNOKX
        initialState.put(new Hash("KA9YIOTIOBQLGEKLXOCPPRZDEAPYBPEYDSXWARRDJKNACWNYSWJXHZDEKFCEGJ9XOTBXWAUQPEEHTZGHC"), 1_000_000_000_000L);  // seed: OWDQPPZIWNSWVIWHJWKNDYMQXHXMUIDSCYJQRYVZEHNWROJJCYRTSFVHODUSUQTWVURKSPKPZHBBAXQAR
        initialState.put(new Hash("LEVWJWXAAJNJVQYJJBIJRZXDESKYXLHYJXICTTCWNRMKTJOVXJFIN9GGH9RADWUOEVHB9MJINPSUHOLDX"), 1_000_000_000_000L);  // seed: ULIJMRKKMEPGYMTHOUXXMSAABJARGMBJQLSVOHQJBLIIGZDKVZPCCOAD9AFOMCV9XVIBKYLTNTI9WERBK
        initialState.put(new Hash("AVRWIKVNGDHXXS9KHJHPWNDDQNPZLDICCOXPYLKBDSL9G9FC9DQGYGAPCWOYYSZS9MGYEXOICDYVHHJMZ"), 1_000_000_000_000L);  // seed: GWGTLTFWCTZPTNQOWSODQCCMBPZXVRNZOJIGMAGJWJBEYNXF9TFAQNPVTJXU9ZUOUPXALIJGEQVBHJORJ
        initialState.put(new Hash("LLKJYMPTNPIVQVIYXBF9XQVXKNLTOAKNSWLLLJWMBTOHMSXUUMFNJBRUIEWHNIHJFSUXDVBV9OZDKMPFA"), 1_000_000_000_000L);  // seed: HJTZQCOTQDKCEHUSKLOFIXZHQHCFRYPUOKAULYUCCDLLZEUDBIH9TWZVOQCEOQ9RMXMPMQOIMLQDZAAM9
        initialState.put(new Hash("ICWAJOLJOCWFLDUGJCZSWBP9CJFMAA9NGYOOFMHZQQVUVIHSJN9GRTRZR9X9GHEOVWZQRVLB9PTVQFQTD"), 1_000_000_000_000L);  // seed: OYFDDRLXGRE9XNNTVNADSNZXOVCINQQZNSITWNAWELWZTEIKBVZ9ZN9JZQYSWHXZF9QNKONFO9RGUYBQY
        initialState.put(new Hash("DSSRHJDNRTRFZXXGNNPZQBBVHIQKIQZLJIJQKEZTFENKJ9UXPXDZAGCYC9LOCIIQNSG9HPPAZOMWJGCYA"), 1_000_000_000_000L);  // seed: ENCEVDYLZ9J9SJQWJBCYFLZXRNF9VW9LHL9HUTHHSFZVX9SDOWMBKCIXRTXP9HEWCXM9UQPDVCFJINPHU
        initialState.put(new Hash("KKXHNRAPFT9NYOQSWCRZGZVDPJDYQADWYFLCLBKXEWGSNOJIIOXNMNOJZZUPD9HCOZKWCVXXDAONGYQUX"), 1_000_000_000_000L);  // seed: HY9TTJKFILSZIXAOHI9SGJFGTRHCDSQRGGG9OLUSZFEGFCJMXKPQFGF9LVNHLZNPZO9AHRQVIQEWTBLJN
        initialState.put(new Hash("JWMRGOARPCCYCXJTGBHYWDLIZCTFFOGRCCZRRYCNFYHQRYZZZYLHPLMNHJYJTVJEXCNIAJDVQSQRBHNZZ"), 1_000_000_000_000L);  // seed: MLI9WFRJWWZCIWHJK99FJPL9EESRNDZV9FLAQHKHABFHPYFRTOPOBSOHCWBJHLUKGUPJELKBRIKOWHGOY
        initialState.put(new Hash("GEMI9LQXYYHZNZCVL9KHNZUTJOFWCXASZLNZUISNFMUCTGLBCUAIHWNZAJJPK9JGMFYRMWXRSKUTWWSWA"), 1_000_000_000_000L);  // seed: RDLQRUGMSCRTOBJO9PKOOMRROJKLILMDFK9NJJFIWFZWPODFQJODKUZLEV9JWBMICLBOHFDWTKLTDDKPE
        initialState.put(new Hash("QJUVSZNSN9XJ9YSPWCMZZQWT9VDGZXZZEUYXO9Y9QWSMYCCRJEOFVMUNGJZJSEVAOWNQJGOHHMQJDTYLB"), 1_000_000_000_000L);  // seed: 9RNBWHFJUZPFEGHEYHNIOBGXTPVEYRMIVEVOLKAWJFMINEPNDAUW9ZELHGLGYHSMBAAZNBCPWYWQWA9PV
        initialState.put(new Hash("LFEMAXCJSBRKYBOFNDGZMKDWRCIISNUJZKTFVUASVWUIGNTNOMIYAFFDBNOVFHJBXNMCZOWXNJUUQCUUD"), 1_000_000_000_000L);  // seed: FFHMTOCZMTFZFYICNZLNFEBVJNZCYOZN9CXYUOKOFQULWSTUSPFOIOJYUCLFM9ELHACXWSKDCUVBCGTU9
        initialState.put(new Hash("CFSHZTVZQIQCEBCADEFVNDXUCAIQUKXQR9LPJWOFQXWJJUUIH9XSHAYGZYJQDK9FTPULCLQCPWBGGGSCC"), 1_000_000_000_000L);  // seed: HRGEXRNXEQSPZWOGO9ZVXVDWGQ9OY9NPKIBLKPHGLPOOBTBHMMYXPPGAXGVXSJQSUZNAJK9CKGRUAYM9D
        initialState.put(new Hash("OOFQNNPXGNHOQ9ODTDO9ACKSFMATINV9FPKGHWGONGHLISNBLHRHSZKGWYCYSYFNAGAVWZAVHOJKZMUQX"), 1_000_000_000_000L);  // seed: NKPESJCLHPHJVKUHRDHILMDZYXPOVKTGDFIDRWPECQVQCXJZCILJTRVAEIXGMEXVJJNXLOCEDGKASFZXO
        initialState.put(new Hash("XP9CMKHIZVVWVKLADNREMEHBGYQXFTHPJWZKDCLSFHFUEPFIKAVSCREDSU9XFZIEBLVDB9KHWFVDHCEEX"), 1_000_000_000_000L);  // seed: ZSGZSNIFUCDVCXODCUZTBJWBAWQAZKYVQSGBGJSVWTOYXAFROYOE9KOJZGGIMIDMLPTFJHIRENJDLJWQU
        initialState.put(new Hash("OJIMUIUCXAOPGWXAWNSQ9RANEMEYOVAQSJOHGBHMPVNMPOKMYQJPGSIMWGNHAPPRVKKKWUBZRMIMODNY9"), 1_000_000_000_000L);  // seed: XBBKNEVXDSWHSVRNCKVCFOBGNLDMVHVLAZ99LMNCCMVOHYDSDULYWMZLRGPYSGIS9PULDGUIHEIKO9ZYQ
        initialState.put(new Hash("MMEBKSNGRIPUV9PBZVUVIAFDJJTR9EEJHWUFL99GZYJKYBKMZEZZRW9ENWMQHOEPPMEP9ABNLKGRYEUWD"), 1_000_000_000_000L);  // seed: YICLEHVD9YTDNTXVDNQYVHV9RQJPUXRNLAZIZXBZFMECNQF99OBN9QHPOXUOWTXRNIEIXPAODT9COOJUF
        initialState.put(new Hash("ZXBYLCXRS9NEQTJSGHJXQIVHZMGNCNYISADNFF9BVJARPQ9GRAZOATYQPYQZR9UZLRRENBPBQPSECXOCC"), 1_000_000_000_000L);  // seed: PUPVNFSZCQWMBXQNM9TRBWYBEMBJAS9MFLWGSVJPREPNZJKLQBLIVBNOSJPEKQDPDUBQNWEUXQDKUS9XF
        initialState.put(new Hash("MRVRCCMPIQAUGJ9IPUKNBMMEDKQHUFZONVXZ9XXAE9KQXXEWMPLXFA9UNODLCVAJBRZBHOVIPXYUMWS9B"), 1_000_000_000_000L);  // seed: PDLCEIKVMIKFRTPWJYZBOVHVXOQNQBPRXZOERHXXAVLWUYJHMEKDGEEOYUMWMJTDQRWHHDVBQBEIOGSMA
        initialState.put(new Hash("PADFUHNAQOQVLHA9JKRXEGQG9OTSBIVRYRREA9TXGKQOZMEGORRXPN9P9BEEI9GJMEWZNPKLWJSLLWPQX"), 1_000_000_000_000L);  // seed: BZBARBHPUVTWRXXVPFXLEEEYHYDRQNCKWAOXVPBTOGGRUMPALCVAKTTKTUSBCESBP9QXLODQHHCCMZVBK
        initialState.put(new Hash("WVTMEYY9YWPTYWMFGHDZBBFPNLQTPGMYLR9AAKZAOIMNGVLOGXIEMUNLJUTTDK9AQBPMZQVG9GEROGXEB"), 1_000_000_000_000L);  // seed: ESIBGSJKYNMCTSJJNYALJKNJTP9BNNPZYDDGHVGPT9YCIYGZDIEWUTVIOGJUZ9MZIZA9EUPTHCITAABSH
        initialState.put(new Hash("RBZNPAVAQXKGIOWVLFJKMAOCDHLRXOZIOIYSJYZGPI9VDHLXSTUFXCKATAPBUVEUSJFMFZCLXGCLDYSCW"), 1_000_000_000_000L);  // seed: RHZASAOSBLRDCKBSGHZLAEUESHMOECLXKGRACCZIFIURPIZOUNGYZYCYQKJWPAIXXKUHZBRESQSCKUEPU
        initialState.put(new Hash("XMZUBNZSDIQFJDGN9NVJDPKOTYP9YBAPHBHBEOZACTWWLCULWARGXXPDHRVITNZBHAHPJYFDPH9SSWVTC"), 1_000_000_000_000L);  // seed: OHKCNAIYO9YCTYMOCKSS9AUUUYDN9IEHKNOVD9DTMSHUFXLXXAHFZCRCGGVKBCMGNTJMZLTSQQLPBHBGK
        initialState.put(new Hash("QURBDUHHLWJPSNBNNFAIRKJQ9DTJOLFEATWNTALEMKYHKACGACFPBDHOBSAPPVRTGIJTAUNQ9KLATBPBC"), 1_000_000_000_000L);  // seed: XPHTUULWX9PKMOIJOOSMPJUPHILVUIABYYQGLQQHOAGPCXARRSCYCGB9YSIKJHVAKTZTITMPYICVOREWW
        initialState.put(new Hash("SNKDHDVXDH9NIXNMGIOLBDIYIHIKAAZAKNRUAX9CGCEREGWNYHFQQBPVVROVJEBXQQLUL9XECFTGQOKUC"), 1_000_000_000_000L);  // seed: Q9YDLEPZDSZPJGVEHKXURFJVSQWHF9OEDKUYKCEKPAOOPQEWTPVPQNRUXMGRQ9TRCOEKKWZQQTWOJNUSF
        initialState.put(new Hash("AYUDJTONEOCVVCEKLUENTZSQCVIPZZMSJWSMUWMHXDRQOIODVBPROBAJWI9IGQKSAMP9XARZBSLQTZCIW"), 1_000_000_000_000L);  // seed: CFCNH9EQKJEALAPHUCGPKBNJJR9VCHOOTOVVGLEUACDUQXRJP9VAQACMYIDYGDTSLI9OKRRSSTXLEVRDV
        initialState.put(new Hash("DYEKSKFMOBEJY9LZDVKKOVKJPEOSBFYGYDBKZAVTJCDVXYDMNITZEJNXUKVTLNKPIZCNROOYNDDDHDENA"), 1_000_000_000_000L);  // seed: BTQZYDHCYSZBK9VVNGLUNE9TTMZUWQPPI9FAYFZOG9DTNBTBHQDWIDBBHTO9NZFZWHXAEBFHWCMCPSKCK
        initialState.put(new Hash("TSEQRTKCQISTUQMYZCLVZMMJA9ZOGKNA9TIXWLRPRYRVNUFXNSGIZVP9PZEQAIJGVYFO9JNUWOPRDIQWC"), 1_000_000_000_000L);  // seed: SKUASSSPQFFWGVYLVXUZYGMMXCYSKLCMWXYNZXERSWVIMZQZYHGISXGO9SDKXTEENWGRQUEGIQESXDLUC
        initialState.put(new Hash("JFO9GUXYZXQWNLCQNURJITHLGHNOOASQNLDCXCBBESYYLCYMRVPNYWRXOOQPDFXJTEVGPR9MDRMURLVSD"), 1_000_000_000_000L);  // seed: CDAIIDJOMZPJWGZDGCIFSFNUC9WWGWQARCJLFBWKRKVYPVONAWXVTKK9XPNTGH9LFXUPCJK9BLCAWEMHZ
        initialState.put(new Hash("YQAJZEOCBXDTYUYAAMMKISPMNLONYDADADSIEHRNJGLESGFSFLEMDSEDNO9IRSXPRHCSGPYYNVNECBSRZ"), 1_000_000_000_000L);  // seed: GBSUHENLOOFPTJEFXEJZHGUTSFZXDKWAOTYVWYIPWCCKJFYYUNRWZGQQBEAQCKVTOZQPSIBNDVUXZ9KCX
        initialState.put(new Hash("MCTUQLNRHHJTJXOTCOKEMNYIXNFNDMIFFN9JOOQJGIJTLQGKQMNVTIRDVPNDJLONRCQERHDWBKLKRRMT9"), 1_000_000_000_000L);  // seed: ZEIKOLYUEXBZIIAULSG9RIPCLCHBNRHNQLQLHVESFHVKETFPHYHUNGXPLVARXRMZSFSFSBIEUDMEQRFM9
        initialState.put(new Hash("KRTEHTKAQOHNEEUVUG9GBEAOSLML9ASQOYDEYMRCFBBTOMFSCLDGVLEUZTZDJRVLGIMFOKIZCDHHBUYJ9"), 1_000_000_000_000L);  // seed: YYDTMW9WZFW9MKBJIC9KLCPGAMOMUVMJFUQP9ACSUYJSJDLNUVCCNXRKN9ZKLRHJEEKMXQUUNUCUTYKDF
        initialState.put(new Hash("VNJQEOIHFADJANCCV9MLQNMQYDZMUQP9XATXPSRD9WVQUURSSYEE99I9FSW9VYYNJOQJOBX9RDURQ9TO9"), 1_000_000_000_000L);  // seed: IOTNVC9SNYYEHQGCZOBAYYTSNHDZBXOSUCYNFEVHHXUQEAPXNMEDOGLQUKXUKMBUV9CFUZBDHIAPBKSHS
        initialState.put(new Hash("VASGWSZ99JWUMQKEDCEQTZFKBIKPNOCZUOQSMGHIRT9CMOMYLSEYB9YHEGYHXXGS9HIEDREBLRCEJ9HBD"), 1_000_000_000_000L);  // seed: SMOGOTNYSSUTLINURQ9ACQSCTJYNZBAAIMHXLCJYLUQCQGVAIFFOMDDUMADCNDPDESQXEKASYIRJOWQ9E
        initialState.put(new Hash("PJMMURNADBRTTHOKZBZUTEEFWIBTFIZBXJPEXKUKHFUYXQMWJKPDG9G9NMACAYJO9FXRUIVAWTOEPYKSW"), 1_000_000_000_000L);  // seed: SVZXCNW9RAHIHCHUJKGGWTUDEDHBPLYXIVUMLBCPQUNIQBLKNCXBJWHLOVGAVOPNIMVJVZZFIYSVNHOIP
        initialState.put(new Hash("MT9LHJS9GYKCP9EHHYQTBUHXWJLUKBUKLBOSIMFEJFNADCOTFTONFJYWOLWYYKNHSLAJMAASJAXYWDKLX"), 1_000_000_000_000L);  // seed: MBYQERWKYXEXEXZ9SFUKKVDAJENPFQKQTNJMGNWZXNTEDAUZFWKW9JMJ9LHUBQFPEOYNQVTNHPWACUHZW


        latestSnapshot = new Snapshot(initialState, 0);
        initialSnapshot = new Snapshot(latestSnapshot);
    }

    public static final Object latestSnapshotSyncObject = new Object();
    private final Map<Hash, Long> state;
    private int index;

    public int index() {
        return index;
    }

    public Snapshot(Snapshot snapshot) {
        state = new HashMap<>(snapshot.state);
        this.index = snapshot.index;
    }

    private Snapshot(Map<Hash, Long> initialState, int index) {
        state = new HashMap<>(initialState);
        this.index = index;
    }

    public Map<Hash, Long> getState() {
        return state;
    }

    public Map<Hash, Long> diff(Map<Hash, Long> newState) {
        return newState.entrySet().parallelStream()
                .map(hashLongEntry ->
                        new HashMap.SimpleEntry<>(hashLongEntry.getKey(),
                                hashLongEntry.getValue() -
                                        (state.containsKey(hashLongEntry.getKey()) ?
                                                state.get(hashLongEntry.getKey()): 0) ))
                .filter(e -> e.getValue() != 0L)
                .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
    }

    public Snapshot patch(Map<Hash, Long> diff, int index) {
        Map<Hash, Long> patchedState = state.entrySet().parallelStream()
                .map( hashLongEntry ->
                        new HashMap.SimpleEntry<>(hashLongEntry.getKey(),
                                hashLongEntry.getValue() +
                                        (diff.containsKey(hashLongEntry.getKey()) ?
                                                diff.get(hashLongEntry.getKey()) : 0)) )
                .filter(e -> e.getValue() != 0L)
                .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
        diff.entrySet().stream()
                .filter(e -> e.getValue() > 0L)
                .forEach(e -> patchedState.putIfAbsent(e.getKey(), e.getValue()));
        return new Snapshot(patchedState, index);
    }

    void merge(Snapshot snapshot) {
        state.clear();
        state.putAll(snapshot.state);
        index = snapshot.index;
    }

    boolean isConsistent() {
        long stateValue = state.values().stream().reduce(Math::addExact).orElse(Long.MAX_VALUE);
        if(stateValue != TransactionViewModel.SUPPLY) {
            long difference = TransactionViewModel.SUPPLY - stateValue;
            log.info("Transaction resolves to incorrect ledger balance: {}", difference);
            return false;
        }
        final Iterator<Map.Entry<Hash, Long>> stateIterator = state.entrySet().iterator();
        while (stateIterator.hasNext()) {

            final Map.Entry<Hash, Long> entry = stateIterator.next();
            if (entry.getValue() <= 0) {

                if (entry.getValue() < 0) {
                    log.info("Skipping negative value for address: " + entry.getKey() + ": " + entry.getValue());
                    return false;
                }

                stateIterator.remove();
            }
            //////////// --Coo only--
                /*
                 * if (entry.getValue() > 0) {
                 *
                 * System.out.ln("initialState.put(new Hash(\"" + entry.getKey()
                 * + "\"), " + entry.getValue() + "L);"); }
                 */
            ////////////
        }
        return true;
    }
}
